[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[functions.api]
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[dev]
  framework = "#static"
  targetPort = 8888
